d:\work\work\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([50, 50, 1, 3])) that is different to the input size (torch.Size([50, 1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Epoch [1/3000], Loss: 255.7956
Epoch [51/3000], Loss: 119.1512
Epoch [101/3000], Loss: 80.4070
Epoch [151/3000], Loss: 91.2890
Epoch [201/3000], Loss: 92.5800
Epoch [251/3000], Loss: 87.3641
Epoch [301/3000], Loss: 91.7019
Epoch [351/3000], Loss: 89.5839
Epoch [401/3000], Loss: 83.2968
Epoch [451/3000], Loss: 79.9301
Epoch [501/3000], Loss: 78.5851
Epoch [551/3000], Loss: 85.5716
Epoch [601/3000], Loss: 81.5246
Epoch [651/3000], Loss: 83.6819
Epoch [701/3000], Loss: 84.3354
Epoch [751/3000], Loss: 83.2849
Epoch [801/3000], Loss: 85.7719
Epoch [851/3000], Loss: 83.9283
Epoch [901/3000], Loss: 88.0687
Epoch [951/3000], Loss: 90.5753
Epoch [1001/3000], Loss: 90.4930
Epoch [1051/3000], Loss: 91.4220
Epoch [1101/3000], Loss: 94.6327
Epoch [1151/3000], Loss: 94.7435
Epoch [1201/3000], Loss: 96.5919
Epoch [1251/3000], Loss: 95.5702
Epoch [1301/3000], Loss: 97.0419
Epoch [1351/3000], Loss: 97.6290
Epoch [1401/3000], Loss: 98.7634
Epoch [1451/3000], Loss: 99.4337
Epoch [1501/3000], Loss: 101.3547
Epoch [1551/3000], Loss: 99.9430
Epoch [1601/3000], Loss: 101.6639
Epoch [1651/3000], Loss: 100.2612
Epoch [1701/3000], Loss: 100.1528
Epoch [1751/3000], Loss: 100.6096
Epoch [1801/3000], Loss: 101.0035
Epoch [1851/3000], Loss: 100.2518
Epoch [1901/3000], Loss: 99.3947
Epoch [1951/3000], Loss: 99.6869
Epoch [2001/3000], Loss: 100.2059
Epoch [2051/3000], Loss: 98.8976
Epoch [2101/3000], Loss: 99.8597
Epoch [2151/3000], Loss: 98.9190
Epoch [2201/3000], Loss: 98.3262
Epoch [2251/3000], Loss: 99.4641
Epoch [2301/3000], Loss: 98.8408
Epoch [2351/3000], Loss: 97.0901
Epoch [2401/3000], Loss: 97.5308
Epoch [2451/3000], Loss: 98.7042
Epoch [2501/3000], Loss: 97.9352
Epoch [2551/3000], Loss: 97.1793
Epoch [2601/3000], Loss: 97.6966
Epoch [2651/3000], Loss: 97.0304
Epoch [2701/3000], Loss: 97.7299
Epoch [2751/3000], Loss: 97.0808
Epoch [2801/3000], Loss: 97.9370
Epoch [2851/3000], Loss: 97.4970
Epoch [2901/3000], Loss: 97.5323
Epoch [2951/3000], Loss: 97.7851
[1826 2029 4406 4459 4834]
d:\work\work\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([5, 5, 1, 3])) that is different to the input size (torch.Size([5, 1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
[ 282 1381 2184 2501 4459]
[2104 2488 2810 3470 4013]
[1545 1725 2655 2656 4473]
[2712 2977 3143 3891 3924]
[ 624 1270 3738 4623 4975]
[ 701 1620 1848 3957 4229]
[ 588 1709 3364 3620 4450]
[ 957 2056 2149 2300 3867]
[ 818 2745 3277 3754 4278]
[1311 2957 3033 3097 3784]
[ 163 2372 4336 4345 4422]
d:\work\work\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([1, 5, 1, 3])) that is different to the input size (torch.Size([5, 1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.