LSTMModel(
  (lstm): LSTM(3, 16, batch_first=True)
  (fc): Linear(in_features=16, out_features=3, bias=True)
)
LSTMModel(
  (lstm): LSTM(3, 512, batch_first=True)
  (fc): Linear(in_features=512, out_features=3, bias=True)
)
d:\work\work\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([50, 1, 3])) that is different to the input size (torch.Size([50, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Epoch [1/10000], Loss: 252.3409
Epoch [501/10000], Loss: 73.9773
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.